### ISSUE TITLE
ws01_ovf.7z.001: ws01_ovf\ws01-disk1.vmdk - 该文件已损坏，或需要其余压缩分卷。 出现错误

### ISSUE THREAD

**Issue by N1sh3xll** [0range-x/dragon-lab#1]
ws01和ws02可以重新发一下吗，vmdk - 该文件已损坏。
![image](https://github.com/0range-x/dragon-lab/assets/38280908/5197497d-95e9-4923-9086-3b2795782a9e)

**Comment by 0range-x** [comment]
链接: https://pan.baidu.com/s/1iydC0NJElrA7zwegwPAEOA?pwd=geft 
有其他师傅已经搭好了，应该没啥问题

**Comment by N1sh3xll** [comment]
还有sql01和sql02的vmdk好像也损坏了。

> 链接: https://pan.baidu.com/s/1iydC0NJElrA7zwegwPAEOA?pwd=geft 有其他师傅已经搭好了，应该没啥问题

好吧，是百度网盘辣鸡丢包了，刚刚重新下载了几次才可以。
